version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  - develop
environment:
  NugetAPIKey:
    secure: zvkaZiaBXVko+3ZzuSb7W6DTUJmHX98XgEhKs28SnGD+4TM3gzhPxVnNWSmBhXEx
install:
- ps: >-
    Install-PackageProvider -Name NuGet -Force | Out-Null

    Install-Module 'PowerShellGet' -Scope CurrentUser -Force -AllowClobber

    Install-Module 'powershell-yaml' -Scope CurrentUser -Force -AllowClobber
build_script:
- ps: .\build.ps1 -Revision "$env:APPVEYOR_BUILD_NUMBER" -Suffix "$env:APPVEYOR_REPO_BRANCH"
deploy_script:
- ps: Publish-Module -Path .\UnitySetup -NugetAPIKey $env:NugetAPIKey
for:
-
  branches:
    only:
    - master
  build_script:
  - ps: .\build.ps1 -Revision "$env:APPVEYOR_BUILD_NUMBER"

